# Generated by Django 3.2.7 on 2021-10-11 14:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=100)),
                ('subject_description', models.CharField(max_length=500)),
                ('lesson_number', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('lesson_name', models.CharField(max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='uploads/covers/')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.fileLocation)),
            ],
        ),
    ]
