# Generated by Django 3.2.7 on 2021-10-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
            options={
                'verbose_name': 'Lookup Type',
                'verbose_name_plural': 'Lookup Types',
                'db_table': 'lookuptype',
            },
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=500)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('lookup_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lookuptype')),
            ],
            options={
                'db_table': 'lookup',
            },
        ),
    ]
