# Generated by Django 3.2.7 on 2021-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lookup_lookuptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lookuptype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
